### ISSUE TITLE
Problem to download the test set?

### ISSUE THREAD

**Issue by tianqig** [fdalvi/cat-detector#1]
When I tried to download the test set with the following command:
`$ curl -o test_set.zip https://raw.githubusercontent.com/CMIST/HiringExercise_MLCVEngineer/master/test_set.zip`

it worked, seems the test set is very small in size, then when unzip, got the following error message:
`$ unzip test_set.zip`
Archive:  test_set.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test_set.zip or
        test_set.zip.zip, and cannot find test_set.zip.ZIP, period.

Please help

Thanks

**Comment by fdalvi** [comment]
Hi @tianqig,

It seems like the team who was interviewing me has made the test set private! Unfortunately there is not much we can do about it - however, what you can do is create your own test set by including pictures of cats and non-cats! The original test set only had about 100 or so images, so it should not be too hard to create a similar set.

Good luck,
Fahim

**Comment by adekability** [comment]
Hi @fdalvi,
Don't you have a tree of file structure and what files should be in that files?
Or it all should be the same as in train file catalog?
Thanks for sharing code of cat-detector!
